package com.agentflow.web.run;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import java.time.Duration;
import java.util.UUID;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class CommitFaultFixtureTest {

    private static final Duration WAIT = Duration.ofSeconds(2);

    @Test
    void failureAtRealBeforeCommitBoundaryRollsBackTheRow() {
        Database database = database();
        CommitFaultFixture fault = new CommitFaultFixture(CommitFaultFixture.Mode.ROLLBACK_BEFORE_COMMIT);

        assertThatThrownBy(() -> fault.execute(database.transactions(), () -> database.insert("before")))
                .isInstanceOf(CommitFaultFixture.BeforeCommitFailure.class);

        assertThat(database.rowCount()).isZero();
    }

    @Test
    void lostConfirmationAfterCommitLeavesTheCommittedRowVisible() throws Exception {
        Database database = database();
        CommitFaultFixture fault = new CommitFaultFixture(CommitFaultFixture.Mode.LOSE_CONFIRMATION_AFTER_COMMIT);

        assertThatThrownBy(() -> fault.execute(database.transactions(), () -> database.insert("after")))
                .isInstanceOf(CommitFaultFixture.CommitOutcomeUnknownException.class);

        assertThat(fault.awaitCommitReturned(WAIT)).isTrue();
        assertThat(database.rowCount()).isEqualTo(1);
    }

    @Test
    void unresolvedIoBlocksTheCallerAfterTheDatabaseHasCommitted() throws Exception {
        Database database = database();
        CommitFaultFixture fault = new CommitFaultFixture(CommitFaultFixture.Mode.UNRESOLVED_IO_AFTER_COMMIT);
        ExecutorService executor = Executors.newSingleThreadExecutor();
        try {
            Future<Integer> future = executor.submit(
                    () -> fault.execute(database.transactions(), () -> database.insert("pending")));

            assertThat(fault.awaitIoPending(WAIT)).isTrue();
            assertThat(future.isDone()).isFalse();
            assertThat(database.rowCount()).isEqualTo(1);

            fault.releaseIo();
            assertThatThrownBy(() -> future.get(WAIT.toMillis(), TimeUnit.MILLISECONDS))
                    .isInstanceOf(ExecutionException.class)
                    .hasCauseInstanceOf(CommitFaultFixture.CommitOutcomeUnknownException.class);
        } finally {
            fault.releaseIo();
            executor.shutdownNow();
            assertThat(executor.awaitTermination(WAIT.toMillis(), TimeUnit.MILLISECONDS)).isTrue();
        }
    }

    @Test
    void visibilityDelayCanHideThenRevealAnActuallyCommittedRow() {
        Database database = database();
        CommitFaultFixture fault = new CommitFaultFixture(CommitFaultFixture.Mode.DELAY_COMMITTED_ROW_VISIBILITY);

        fault.execute(database.transactions(), () -> database.insert("delayed"));

        assertThat(database.rowCount()).isEqualTo(1);
        assertThat(fault.observeCommittedRow(database::rowCount, 0)).isZero();
        fault.revealCommittedRow();
        assertThat(fault.observeCommittedRow(database::rowCount, 0)).isEqualTo(1);
    }

    private Database database() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("create table fixture_row (id integer generated by default as identity primary key, payload varchar(40))");
        return new Database(jdbc, new TransactionTemplate(new DataSourceTransactionManager(dataSource)));
    }

    private record Database(JdbcTemplate jdbc, TransactionTemplate transactions) {
        int insert(String value) {
            return jdbc.update("insert into fixture_row(payload) values (?)", value);
        }

        int rowCount() {
            return jdbc.queryForObject("select count(*) from fixture_row", Integer.class);
        }
    }
}
